### ISSUE TITLE
Bug in Integrator

### ISSUE THREAD

**Issue by Jerry-Kwan** [torchmd/torchmd#41]
There is a bug in the `step()` method in the Integrator class, code is as follow:

```python
def step(self, niter=1):
    s = self.systems
    masses = self.forces.par.masses
    natoms = len(masses)
    for _ in range(niter):
        _first_VV(s.pos, s.vel, s.forces, masses, self.dt)
        pot = self.forces.compute(s.pos, s.box, s.forces)
        if self.T:
            langevin(s.vel, self.gamma, self.vcoeff, self.dt, self.device)
        _second_VV(s.vel, s.forces, masses, self.dt)

    Ekin = np.array([v.item() for v in kinetic_energy(masses, s.vel)])
    T = kinetic_to_temp(Ekin, natoms)
    return Ekin, pot, T
```

In the ***first*** loop, if s.forces is not updated according to the current s.pos, then the output would be wrong.

Take the code in your `tutorial.ipynb` for example, pos is updated by `wrap()` in every loop of simulation while forces are not updated after `wrap()`, causing the `integrator.step()` in the next loop to be wrong due to the old forces.

**Comment by stefdoerr** [comment]
Wrapping does not affect the forces of a simulation (excluding the case where the atoms travel so far you run into numerical issues). It's just a visual aid.

The forces are updated before wrap inside the `step` function, so they are updated at every loop iteration. In the tutorial.ipynb we calculate the forces once before getting into the loop so that they are not empty.

Maybe I don't understand what you mean but it doesn't seem wrong to me
