### ISSUE TITLE
Bug in Velocity-Verlet Code?

### ISSUE THREAD

**Issue by diningphil** [torchmd/torchmd#42]
I have a question about the implementation of the Velocity Verlet integrator.

[At this line](https://github.com/torchmd/torchmd/blob/cb7ff8723757f7b3e8318374a6508aa77371b3fa/torchmd/integrator.py#L31) should there not be another acceleration contribution?

If I look at the definitions from [Wikipedia](https://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet), the implementation of the position equation seems correct but not the one for the velocity.

Could you please help me understand? As a non-physicist it is likely that this is not a bug and I am missing something!

Thank you,
Federico

**Comment by stefdoerr** [comment]
![image](https://github.com/torchmd/torchmd/assets/7935362/390b7cb8-8420-469f-b118-e63b36b3058a)
It's an implementation of this exact algorithm. It's just that we also make a velocity update in the first step instead of doing both in the second step because it's used in the langevin step for the thermostat
